#include (CMakeDependentOption)
include (FeatureSummary)

if (UNIX)
# pkg_check_modules (PKG_DHCP REQUIRED bind-exports isc-dhcp-client)
# pkg_check_modules (PKG_JSON json-c)
# if (NOT PKG_JSON_FOUND)
#  message (WARNING "could not find json-c, continuing")
#  set (DHCLIENT_SUPPORT_ENABLE OFF)
# endif (NOT PKG_JSON_FOUND)
 if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  if (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
   set (JSON_LIB_FILE libjson-c.so)
  else ()
   set (JSON_LIB_FILE libjson-c.so.5)
  endif (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
 endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
 find_library (JSON_LIBRARY ${JSON_LIB_FILE}
               DOC "searching for ${JSON_LIB_FILE}")
 if (NOT JSON_LIBRARY)
  message (WARNING "could not find ${JSON_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found json library \"${JSON_LIBRARY}\"")
 endif (NOT JSON_LIBRARY)

#  set (ISC_LIB_FILE libisc-export.so)
# set (ISC_LIB_FILE libisc-export.so.1100)
 if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  if (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
   set (ISC_LIB_FILE libisc.so.1105)
  else ()
   set (ISC_LIB_FILE libisc.so)
  endif (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
 endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
 find_library (ISC_LIBRARY ${ISC_LIB_FILE}
               DOC "searching for ${ISC_LIB_FILE}")
 if (NOT ISC_LIBRARY)
  message (WARNING "could not find ${ISC_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found ISC library \"${ISC_LIBRARY}\"")
 endif (NOT ISC_LIBRARY)

 pkg_check_modules (PKG_KRB5_GSSAPI krb5-gssapi)
 if (NOT PKG_KRB5_GSSAPI_FOUND)
  message (WARNING "could not find krb5-gssapi, continuing")
 endif (NOT PKG_KRB5_GSSAPI_FOUND)

# set (GEOIP_LIB_FILE libGeoIP.so.1)
 set (GEOIP_LIB_FILE libGeoIP.so)
 find_library (GEOIP_LIBRARY ${GEOIP_LIB_FILE}
               DOC "searching for ${GEOIP_LIB_FILE}")
 if (NOT GEOIP_LIBRARY)
  message (WARNING "could not find ${GEOIP_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found GeoIP library \"${GEOIP_LIBRARY}\"")
 endif ()

# set (DNS_LIB_FILE libdns-export.so)
#  set (DNS_LIB_FILE libdns-export.so.1104)
 if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  if (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
   set (DNS_LIB_FILE libdns-export.so.1109)
  else ()
   set (DNS_LIB_FILE libdns.so)
  endif (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
 endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
 find_library (DNS_LIBRARY ${DNS_LIB_FILE}
               DOC "searching for ${DNS_LIB_FILE}")
 if (NOT DNS_LIBRARY)
  message (WARNING "could not find ${DNS_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found dns library \"${DNS_LIBRARY}\"")
 endif (NOT DNS_LIBRARY)

# set (ISC_CFG_LIB_FILE libisccfg-export.so)
#  set (ISC_CFG_LIB_FILE libisccfg-export.so.163)
 if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  if (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
   set (ISC_CFG_LIB_FILE libisccfg.so.163)
  else ()
   set (ISC_CFG_LIB_FILE libisccfg.so)
  endif (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
 endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
 find_library (ISC_CFG_LIBRARY ${ISC_CFG_LIB_FILE}
               DOC "searching for ${ISC_CFG_LIB_FILE}")
 if (NOT ISC_CFG_LIBRARY)
  message (WARNING "could not find ${ISC_CFG_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found isccfg library \"${ISC_CFG_LIBRARY}\"")
 endif (NOT ISC_CFG_LIBRARY)

#  set (IRS_LIB_FILE libirs.a)
# set (IRS_LIB_FILE libirs-export.so.161)
 if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  if (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
   set (IRS_LIB_FILE libirs.so.161)
  else ()
   set (IRS_LIB_FILE libirs.so)
  endif (${LSB_RELEASE_ID_SHORT} MATCHES "Ubuntu")
 endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
 find_library (IRS_LIBRARY ${IRS_LIB_FILE}
               DOC "searching for ${IRS_LIB_FILE}")
 if (NOT IRS_LIBRARY)
  message (WARNING "could not find ${IRS_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found irs library \"${IRS_LIBRARY}\"")
 endif (NOT IRS_LIBRARY)

 set (OMAPI_LIB_FILE libomapi.a)
# set (OMAPI_LIB_FILE libomapi.so)
 find_library (OMAPI_LIBRARY ${OMAPI_LIB_FILE}
               HINTS /usr/lib64 /usr/lib
               PATH_SUFFIXES dhcp x86_64-linux-gnu
               DOC "searching for ${OMAPI_LIB_FILE} (system paths)")
 if (NOT OMAPI_LIBRARY)
  message (WARNING "could not find ${OMAPI_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found omapi library \"${OMAPI_LIBRARY}\"")
 endif (NOT OMAPI_LIBRARY)

  set (DHCPCTL_LIB_FILE libdhcpctl.a)
# set (DHCPCTL_LIB_FILE libdhcpctl.so)
 find_library (DHCPCTL_LIBRARY ${DHCPCTL_LIB_FILE}
               HINTS /usr/lib64 /usr/lib
               PATH_SUFFIXES dhcp x86_64-linux-gnu
               DOC "searching for ${DHCPCTL_LIB_FILE} (system paths)")
 if (NOT DHCPCTL_LIBRARY)
  message (WARNING "could not find ${DHCPCTL_LIB_FILE}, continuing")
 else ()
  message (STATUS "Found dhcpctl library \"${DHCPCTL_LIBRARY}\"")
 endif (NOT DHCPCTL_LIBRARY)

 if (JSON_LIBRARY AND ISC_LIBRARY AND GEOIP_LIBRARY AND DNS_LIBRARY AND ISC_CFG_LIBRARY AND IRS_LIBRARY AND OMAPI_LIBRARY)
  option (DHCLIENT_SUPPORT "enable ISC dhclient support" ON)
  add_feature_info (dhclient DHCLIENT_SUPPORT "support ISC dhclient")
  if (DHCLIENT_SUPPORT)
   add_definitions (-DDHCLIENT_SUPPORT)
  endif (DHCLIENT_SUPPORT)
 endif (JSON_LIBRARY AND ISC_LIBRARY AND GEOIP_LIBRARY AND DNS_LIBRARY AND ISC_CFG_LIBRARY AND IRS_LIBRARY AND OMAPI_LIBRARY)

 # *TODO*: test this first
 option (DHCPD_SUPPORT "enable dhcpd support" OFF)
 add_feature_info (dhcpd DHCPD_SUPPORT "support dhcpd")
 if (DHCPD_SUPPORT)
  add_definitions (-DDHCPD_SUPPORT)
#  add_compile_options (-std=c++11)
 endif (DHCPD_SUPPORT)
elseif (WIN32)
 option (WLANAPI_DHCP_SUPPORT "enable wlanapi DHCP support" ON)
 add_feature_info (wlanapi_dhcp WLANAPI_DHCP_SUPPORT "support wlanapi DHCP")
 if (WLANAPI_DHCP_SUPPORT)
  add_definitions (-DWLANAPI_DHCP_SUPPORT)
 endif (WLANAPI_DHCP_SUPPORT)
endif ()
option (FRAMEWORK_DHCP_SUPPORT "enable framework DHCP support" ON)
add_feature_info (framework_dhcp FRAMEWORK_DHCP_SUPPORT "support framework DHCP (ACENetwork)")
if (FRAMEWORK_DHCP_SUPPORT)
 add_definitions (-DFRAMEWORK_DHCP_SUPPORT)
endif (FRAMEWORK_DHCP_SUPPORT)
