# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ACENetwork ACENetwork_Client ACENetwork_Server ACENetwork_Protocol_DHCP ACENetwork_Protocol_HTTP ACENetwork_Protocol_IRC ACENetwork_Protocol_BitTorrent ACENetwork_WLAN)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ACENetwork
add_library(ACENetwork STATIC IMPORTED)

set_target_properties(ACENetwork PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/libnl3;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACENetwork/src/../../Common/cmake;/mnt/win_d/projects/ACENetwork/src/../../Common/src;/mnt/win_d/projects/ACENetwork/src/../../Common/src/timer;/mnt/win_d/projects/ACENetwork/src/../../ACEStream/cmake;/mnt/win_d/projects/ACENetwork/src/../../ACEStream/src;/mnt/win_d/projects/ACENetwork/src/../../ACEStream/src/modules/lib;/mnt/win_d/projects/ACENetwork/src/../../ACEStream/src/modules/stat;/mnt/win_d/projects/ACENetwork/src/../3rd_party/bison;/mnt/win_d/projects/ACENetwork/clang/src/..;/mnt/win_d/projects/ACENetwork/src/wlan"
)

# Create imported target ACENetwork_Client
add_library(ACENetwork_Client STATIC IMPORTED)

set_target_properties(ACENetwork_Client PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACENetwork/src/client_server/../../../Common/cmake;/mnt/win_d/projects/ACENetwork/src/client_server/../../../Common/src;/mnt/win_d/projects/ACENetwork/src/client_server/../../../Common/src/timer;/mnt/win_d/projects/ACENetwork/src/client_server/../../../ACEStream/cmake;/mnt/win_d/projects/ACENetwork/src/client_server/../../../ACEStream/src;/mnt/win_d/projects/ACENetwork/src/client_server/../../../ACEStream/src/modules/lib;/mnt/win_d/projects/ACENetwork/clang/src/client_server/../..;/mnt/win_d/projects/ACENetwork/src/client_server/../"
)

# Create imported target ACENetwork_Server
add_library(ACENetwork_Server STATIC IMPORTED)

set_target_properties(ACENetwork_Server PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACENetwork/src/client_server/../../../Common/cmake;/mnt/win_d/projects/ACENetwork/src/client_server/../../../Common/src;/mnt/win_d/projects/ACENetwork/src/client_server/../../../Common/src/log;/mnt/win_d/projects/ACENetwork/src/client_server/../../../Common/src/timer;/mnt/win_d/projects/ACENetwork/src/client_server/../../../ACEStream/cmake;/mnt/win_d/projects/ACENetwork/src/client_server/../../../ACEStream/src;/mnt/win_d/projects/ACENetwork/src/client_server/../../../ACEStream/src/modules/lib;/mnt/win_d/projects/ACENetwork/clang/src/client_server/../..;/mnt/win_d/projects/ACENetwork/src/client_server/../"
)

# Create imported target ACENetwork_Protocol_DHCP
add_library(ACENetwork_Protocol_DHCP STATIC IMPORTED)

set_target_properties(ACENetwork_Protocol_DHCP PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../../../Common/cmake;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../../../Common/src;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../../../Common/src/timer;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../../../ACEStream/cmake;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../../../ACEStream/src;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../../../ACEStream/src/modules/lib;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../../../ACEStream/src/modules/stat;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../../3rd_party/bison;/mnt/win_d/projects/ACENetwork/clang/src/protocol/dhcp/../../..;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../..;/mnt/win_d/projects/ACENetwork/src/protocol/dhcp/../../client_server"
)

# Create imported target ACENetwork_Protocol_HTTP
add_library(ACENetwork_Protocol_HTTP STATIC IMPORTED)

set_target_properties(ACENetwork_Protocol_HTTP PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../Common/cmake;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../Common/src;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../Common/src/timer;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../ACEStream/cmake;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../ACEStream/src;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../ACEStream/src/modules/dec;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../ACEStream/src/modules/lib;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../ACEStream/src/modules/net;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../../ACEStream/src/modules/stat;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../../3rd_party/bison;/mnt/win_d/projects/ACENetwork/clang/src/protocol/http/../../..;/mnt/win_d/projects/ACENetwork/src/protocol/http/../..;/mnt/win_d/projects/ACENetwork/src/protocol/http/../../client_server"
)

# Create imported target ACENetwork_Protocol_IRC
add_library(ACENetwork_Protocol_IRC STATIC IMPORTED)

set_target_properties(ACENetwork_Protocol_IRC PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../Common/cmake;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../Common/src;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../Common/src/log;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../Common/src/timer;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../ACEStream/cmake;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../ACEStream/src;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../ACEStream/src/modules/lib;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../ACEStream/src/modules/net;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../../../ACEStream/src/modules/stat;/mnt/win_d/projects/ACENetwork/clang/src/protocol/irc/../../..;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../..;/mnt/win_d/projects/ACENetwork/src/protocol/irc/../../client_server"
)

# Create imported target ACENetwork_Protocol_BitTorrent
add_library(ACENetwork_Protocol_BitTorrent STATIC IMPORTED)

set_target_properties(ACENetwork_Protocol_BitTorrent PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../Common/cmake;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../Common/src;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../Common/src/timer;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../Common/src/ui;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../ACEStream/cmake;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../ACEStream/src;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../ACEStream/src/modules/dec;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../ACEStream/src/modules/lib;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../ACEStream/src/modules/net;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../../ACEStream/src/modules/stat;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../3rd_party/bison;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../../3rd_party/flex;/mnt/win_d/projects/ACENetwork/clang/src/protocol/p2p/bittorrent/../../../..;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../..;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../../client_server;/mnt/win_d/projects/ACENetwork/src/protocol/p2p/bittorrent/../../http"
)

# Create imported target ACENetwork_WLAN
add_library(ACENetwork_WLAN STATIC IMPORTED)

set_target_properties(ACENetwork_WLAN PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/x86_64-linux-gnu;/usr/include/libnl3;/usr/include/dbus-1.0;/usr/lib/x86_64-linux-gnu/dbus-1.0/include;/usr/include/libnm;/usr/include/libmount;/usr/include/blkid;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/media/erik/USB_BLACK/lib/ACE_TAO/ACE;/mnt/win_d/projects/ACENetwork/src/wlan/../../../Common/cmake;/mnt/win_d/projects/ACENetwork/src/wlan/../../../Common/src;/mnt/win_d/projects/ACENetwork/src/wlan/../../../Common/src/dbus;/mnt/win_d/projects/ACENetwork/src/wlan/../../../Common/src/error;/mnt/win_d/projects/ACENetwork/src/wlan/../../../Common/src/math;/mnt/win_d/projects/ACENetwork/src/wlan/../../../Common/src/timer;/mnt/win_d/projects/ACENetwork/src/wlan/../../../Common/src/xml;/mnt/win_d/projects/ACENetwork/src/wlan/../../../ACEStream/cmake;/mnt/win_d/projects/ACENetwork/src/wlan/../../../ACEStream/src;/mnt/win_d/projects/ACENetwork/src/wlan/../../../ACEStream/src/modules/lib;/mnt/win_d/projects/ACENetwork/clang/src/wlan/../..;/mnt/win_d/projects/ACENetwork/src/wlan/..;/mnt/win_d/projects/ACENetwork/src/wlan/../protocol/dhcp"
)

# Import target "ACENetwork" for configuration "Debug"
set_property(TARGET ACENetwork APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACENetwork PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ACENetwork_WLAN;/media/erik/USB_BLACK/lib/ACE_TAO/ACE/lib/libACE.so;/media/erik/USB_BLACK/lib/ACE_TAO/ACE/lib/libACE_SSL.so"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACENetwork/clang/src/libACENetwork.a"
  )

# Import target "ACENetwork_Client" for configuration "Debug"
set_property(TARGET ACENetwork_Client APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACENetwork_Client PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACENetwork/clang/src/client_server/libACENetwork_Client.a"
  )

# Import target "ACENetwork_Server" for configuration "Debug"
set_property(TARGET ACENetwork_Server APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACENetwork_Server PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACENetwork/clang/src/client_server/libACENetwork_Server.a"
  )

# Import target "ACENetwork_Protocol_DHCP" for configuration "Debug"
set_property(TARGET ACENetwork_Protocol_DHCP APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACENetwork_Protocol_DHCP PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;CommonTimer;ACEStream;ACENetwork"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACENetwork/clang/src/protocol/dhcp/libACENetwork_Protocol_DHCP.a"
  )

# Import target "ACENetwork_Protocol_HTTP" for configuration "Debug"
set_property(TARGET ACENetwork_Protocol_HTTP APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACENetwork_Protocol_HTTP PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACENetwork/clang/src/protocol/http/libACENetwork_Protocol_HTTP.a"
  )

# Import target "ACENetwork_Protocol_IRC" for configuration "Debug"
set_property(TARGET ACENetwork_Protocol_IRC APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACENetwork_Protocol_IRC PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACENetwork/clang/src/protocol/irc/libACENetwork_Protocol_IRC.a"
  )

# Import target "ACENetwork_Protocol_BitTorrent" for configuration "Debug"
set_property(TARGET ACENetwork_Protocol_BitTorrent APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACENetwork_Protocol_BitTorrent PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "Common;ACEStream"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACENetwork/clang/src/protocol/p2p/bittorrent/libACENetwork_Protocol_BitTorrent.a"
  )

# Import target "ACENetwork_WLAN" for configuration "Debug"
set_property(TARGET ACENetwork_WLAN APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(ACENetwork_WLAN PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "iw;nl-genl-3;nl-3;dbus-1;nm;gio-2.0;gobject-2.0;glib-2.0;CommonDBus;ACENetwork;ACENetwork_Protocol_DHCP"
  IMPORTED_LOCATION_DEBUG "/mnt/win_d/projects/ACENetwork/clang/src/wlan/libACENetwork_WLAN.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
