// http_reflex_scanner.h generated by reflex 6.3.0 from reflex_scanner.l

#ifndef HTTP_Reflex_Scanner_REFLEX_HTTP_REFLEX_SCANNER_H
#define HTTP_Reflex_Scanner_REFLEX_HTTP_REFLEX_SCANNER_H
#define HTTP_Reflex_Scanner_IN_HEADER 1
#define REFLEX_VERSION "6.3.0"
#define REFLEX_VERSION_MAJOR 6
#define REFLEX_VERSION_MINOR 3

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_8bit
#undef REFLEX_OPTION_batch
#undef REFLEX_OPTION_bison
#undef REFLEX_OPTION_bison_bridge
#undef REFLEX_OPTION_bison_locations
#undef REFLEX_OPTION_debug
#undef REFLEX_OPTION_extra_type
#undef REFLEX_OPTION_flex
#undef REFLEX_OPTION_full
#undef REFLEX_OPTION_header_file
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_never_interactive
#undef REFLEX_OPTION_nodefault
#undef REFLEX_OPTION_noline
#undef REFLEX_OPTION_nomain
#undef REFLEX_OPTION_nostack
#undef REFLEX_OPTION_nostdinit
#undef REFLEX_OPTION_nounistd
#undef REFLEX_OPTION_nounput
#undef REFLEX_OPTION_noyymore
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_perf_report
#undef REFLEX_OPTION_pointer
#undef REFLEX_OPTION_prefix
#undef REFLEX_OPTION_reentrant
#undef REFLEX_OPTION_verbose
#undef REFLEX_OPTION_warn
#undef REFLEX_OPTION_yylineno
#undef REFLEX_OPTION_yywrap

#define REFLEX_OPTION_8bit                true
#define REFLEX_OPTION_batch               true
#define REFLEX_OPTION_bison               true
#define REFLEX_OPTION_bison_bridge        true
#define REFLEX_OPTION_bison_locations     true
#define REFLEX_OPTION_debug               true
#define REFLEX_OPTION_extra_type          HTTP_Reflex_IParser*
#define REFLEX_OPTION_flex                true
#define REFLEX_OPTION_full                true
#define REFLEX_OPTION_header_file         "http_reflex_scanner.h"
#define REFLEX_OPTION_lex                 HTTP_Reflex_Scanner_lex
#define REFLEX_OPTION_lexer               HTTP_Reflex_Scanner_FlexLexer
#define REFLEX_OPTION_never_interactive   true
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_noline              true
#define REFLEX_OPTION_nomain              true
#define REFLEX_OPTION_nostack             true
#define REFLEX_OPTION_nostdinit           true
#define REFLEX_OPTION_nounistd            true
#define REFLEX_OPTION_nounput             true
#define REFLEX_OPTION_noyymore            true
#define REFLEX_OPTION_outfile             "http_reflex_scanner.cpp"
#define REFLEX_OPTION_perf_report         true
#define REFLEX_OPTION_pointer             true
#define REFLEX_OPTION_prefix              HTTP_Reflex_Scanner_
#define REFLEX_OPTION_reentrant           true
#define REFLEX_OPTION_verbose             true
#define REFLEX_OPTION_warn                true
#define REFLEX_OPTION_yylineno            true
#define REFLEX_OPTION_yywrap              true

// --debug option enables ASSERT:
#define ASSERT(c) assert(c)

// --perf-report option requires a timer:
#include <reflex/timer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


#include "http_common.h"
//#include "http_exports.h"
#include "http_reflex_iparser.h"
//#undef http_tokentype
union HTTP_STYPE;
#if !defined HTTP_LTYPE && !defined HTTP_LTYPE_IS_DECLARED
typedef struct HTTP_LTYPE HTTP_LTYPE;
struct HTTP_LTYPE
{
  int first_line;
  int first_column;
  int last_line;
  int last_column;
};
#define HTTP_LTYPE_IS_DECLARED 1
#define HTTP_LTYPE_IS_TRIVIAL 1
#endif
#define YYSTYPE HTTP_STYPE
#define YYLTYPE HTTP_LTYPE
int HTTP_Reflex_Scanner_lex (HTTP_STYPE*, HTTP_LTYPE*, yyscan_t);
#define http_lex HTTP_Reflex_Scanner_lex

void HTTP_Reflex_Scanner_set_extra (HTTP_Reflex_IParser*, yyscan_t);
int HTTP_Reflex_Scanner_get_debug (yyscan_t);
void HTTP_Reflex_Scanner_set_debug (int, yyscan_t);
void HTTP_Reflex_Scanner_set_lineno (int, yyscan_t);
void HTTP_Reflex_Scanner_set_column (int, yyscan_t);


#ifdef __cplusplus

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE ABSTRACT LEXER CLASS                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/flexlexer.h>
typedef reflex::FlexLexer<reflex::Matcher> FlexLexer;

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class HTTP_Reflex_Scanner_FlexLexer : public FlexLexer {
 public:
  HTTP_Reflex_Scanner_FlexLexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, NULL means std::cout by default
      std::ostream *os = NULL)
    :
      FlexLexer(input, os)
  {
    set_debug(true);
    set_perf_report();
  }
  // bison-locations: yylloc_update() tracks lexeme locations
  virtual void yylloc_update(YYLTYPE& yylloc)
  {
    yylloc.first_line = static_cast<unsigned int>(matcher().lineno());
    yylloc.first_column = static_cast<unsigned int>(matcher().columno());
    yylloc.last_line = static_cast<unsigned int>(matcher().lineno_end());
    yylloc.last_column = static_cast<unsigned int>(matcher().columno_end());
  }
  virtual int yylex(void)
  {
    LexerError("HTTP_Reflex_Scanner_FlexLexer::yylex invoked but %option bison-bridge and/or bison-locations is used");
    yyterminate();
  }
  // the flex bison-locations lexer function defined by SECTION 2
  virtual int HTTP_Reflex_Scanner_lex(YYSTYPE& yylval, YYLTYPE& yylloc);
  void perf_report()
  {
    if (perf_report_time_pointer != NULL)
      *perf_report_time_pointer += reflex::timer_elapsed(perf_report_timer);
    std::cerr << "reflex 6.3.0 reflex_scanner.l performance report:\n";
    std::cerr << "  INITIAL rules matched:\n"
      "    rule at line 338 matched " << perf_report_INITIAL_rule[0] << " times, matching " << perf_report_INITIAL_size[0] << " bytes total in " << perf_report_INITIAL_time[0] << " ms\n"
      "    rule at line 342 matched " << perf_report_INITIAL_rule[1] << " times, matching " << perf_report_INITIAL_size[1] << " bytes total in " << perf_report_INITIAL_time[1] << " ms\n"
      "    rule at line 690 matched " << perf_report_INITIAL_rule[2] << " times, matching " << perf_report_INITIAL_size[2] << " bytes total in " << perf_report_INITIAL_time[2] << " ms\n";
    std::cerr << "  request rules matched:\n"
      "    rule at line 348 matched " << perf_report_request_rule[0] << " times, matching " << perf_report_request_size[0] << " bytes total in " << perf_report_request_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_request_rule[1] << " times, matching " << perf_report_request_size[1] << " bytes total in " << perf_report_request_time[1] << " ms\n";
    std::cerr << "  uri rules matched:\n"
      "    rule at line 359 matched " << perf_report_uri_rule[0] << " times, matching " << perf_report_uri_size[0] << " bytes total in " << perf_report_uri_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_uri_rule[1] << " times, matching " << perf_report_uri_size[1] << " bytes total in " << perf_report_uri_time[1] << " ms\n";
    std::cerr << "  version rules matched:\n"
      "    rule at line 370 matched " << perf_report_version_rule[0] << " times, matching " << perf_report_version_size[0] << " bytes total in " << perf_report_version_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_version_rule[1] << " times, matching " << perf_report_version_size[1] << " bytes total in " << perf_report_version_time[1] << " ms\n";
    std::cerr << "  request_headers rules matched:\n"
      "    rule at line 381 matched " << perf_report_request_headers_rule[0] << " times, matching " << perf_report_request_headers_size[0] << " bytes total in " << perf_report_request_headers_time[0] << " ms\n"
      "    rule at line 389 matched " << perf_report_request_headers_rule[1] << " times, matching " << perf_report_request_headers_size[1] << " bytes total in " << perf_report_request_headers_time[1] << " ms\n"
      "    rule at line 397 matched " << perf_report_request_headers_rule[2] << " times, matching " << perf_report_request_headers_size[2] << " bytes total in " << perf_report_request_headers_time[2] << " ms\n"
      "    rule at line 405 matched " << perf_report_request_headers_rule[3] << " times, matching " << perf_report_request_headers_size[3] << " bytes total in " << perf_report_request_headers_time[3] << " ms\n"
      "    rule at line 690 matched " << perf_report_request_headers_rule[4] << " times, matching " << perf_report_request_headers_size[4] << " bytes total in " << perf_report_request_headers_time[4] << " ms\n";
    std::cerr << "  response rules matched:\n"
      "    rule at line 448 matched " << perf_report_response_rule[0] << " times, matching " << perf_report_response_size[0] << " bytes total in " << perf_report_response_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_response_rule[1] << " times, matching " << perf_report_response_size[1] << " bytes total in " << perf_report_response_time[1] << " ms\n";
    std::cerr << "  status rules matched:\n"
      "    rule at line 459 matched " << perf_report_status_rule[0] << " times, matching " << perf_report_status_size[0] << " bytes total in " << perf_report_status_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_status_rule[1] << " times, matching " << perf_report_status_size[1] << " bytes total in " << perf_report_status_time[1] << " ms\n";
    std::cerr << "  reason rules matched:\n"
      "    rule at line 470 matched " << perf_report_reason_rule[0] << " times, matching " << perf_report_reason_size[0] << " bytes total in " << perf_report_reason_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_reason_rule[1] << " times, matching " << perf_report_reason_size[1] << " bytes total in " << perf_report_reason_time[1] << " ms\n";
    std::cerr << "  response_headers rules matched:\n"
      "    rule at line 481 matched " << perf_report_response_headers_rule[0] << " times, matching " << perf_report_response_headers_size[0] << " bytes total in " << perf_report_response_headers_time[0] << " ms\n"
      "    rule at line 489 matched " << perf_report_response_headers_rule[1] << " times, matching " << perf_report_response_headers_size[1] << " bytes total in " << perf_report_response_headers_time[1] << " ms\n"
      "    rule at line 497 matched " << perf_report_response_headers_rule[2] << " times, matching " << perf_report_response_headers_size[2] << " bytes total in " << perf_report_response_headers_time[2] << " ms\n"
      "    rule at line 505 matched " << perf_report_response_headers_rule[3] << " times, matching " << perf_report_response_headers_size[3] << " bytes total in " << perf_report_response_headers_time[3] << " ms\n"
      "    rule at line 690 matched " << perf_report_response_headers_rule[4] << " times, matching " << perf_report_response_headers_size[4] << " bytes total in " << perf_report_response_headers_time[4] << " ms\n";
    std::cerr << "  body rules matched:\n"
      "    rule at line 546 matched " << perf_report_body_rule[0] << " times, matching " << perf_report_body_size[0] << " bytes total in " << perf_report_body_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_body_rule[1] << " times, matching " << perf_report_body_size[1] << " bytes total in " << perf_report_body_time[1] << " ms\n";
    std::cerr << "  chunked_body rules matched:\n"
      "    rule at line 590 matched " << perf_report_chunked_body_rule[0] << " times, matching " << perf_report_chunked_body_size[0] << " bytes total in " << perf_report_chunked_body_time[0] << " ms\n"
      "    rule at line 623 matched " << perf_report_chunked_body_rule[1] << " times, matching " << perf_report_chunked_body_size[1] << " bytes total in " << perf_report_chunked_body_time[1] << " ms\n"
      "    rule at line 631 matched " << perf_report_chunked_body_rule[2] << " times, matching " << perf_report_chunked_body_size[2] << " bytes total in " << perf_report_chunked_body_time[2] << " ms\n"
      "    rule at line 690 matched " << perf_report_chunked_body_rule[3] << " times, matching " << perf_report_chunked_body_size[3] << " bytes total in " << perf_report_chunked_body_time[3] << " ms\n";
    std::cerr << "  chunk rules matched:\n"
      "    rule at line 645 matched " << perf_report_chunk_rule[0] << " times, matching " << perf_report_chunk_size[0] << " bytes total in " << perf_report_chunk_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_chunk_rule[1] << " times, matching " << perf_report_chunk_size[1] << " bytes total in " << perf_report_chunk_time[1] << " ms\n";
    std::cerr << "  data_ rules matched:\n"
      "    rule at line 578 matched " << perf_report_data__rule[0] << " times, matching " << perf_report_data__size[0] << " bytes total in " << perf_report_data__time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_data__rule[1] << " times, matching " << perf_report_data__size[1] << " bytes total in " << perf_report_data__time[1] << " ms\n";
    std::cerr << "  data_2 rules matched:\n"
      "    rule at line 669 matched " << perf_report_data_2_rule[0] << " times, matching " << perf_report_data_2_size[0] << " bytes total in " << perf_report_data_2_time[0] << " ms\n"
      "    rule at line 690 matched " << perf_report_data_2_rule[1] << " times, matching " << perf_report_data_2_size[1] << " bytes total in " << perf_report_data_2_time[1] << " ms\n";
    std::cerr << "  WARNING: execution time measurements are relative:\n  - includes caller's execution time between matches when HTTP_Reflex_Scanner_lex() returns\n  - perf-report instrumentation adds overhead that increases execution times\n" << std::endl;
    set_perf_report();
  }
  void set_perf_report()
  {
    perf_report_INITIAL_rule[0] = 0;
    perf_report_INITIAL_size[0] = 0;
    perf_report_INITIAL_time[0] = 0;
    perf_report_INITIAL_rule[1] = 0;
    perf_report_INITIAL_size[1] = 0;
    perf_report_INITIAL_time[1] = 0;
    perf_report_INITIAL_rule[2] = 0;
    perf_report_INITIAL_size[2] = 0;
    perf_report_INITIAL_time[2] = 0;
    perf_report_request_rule[0] = 0;
    perf_report_request_size[0] = 0;
    perf_report_request_time[0] = 0;
    perf_report_request_rule[1] = 0;
    perf_report_request_size[1] = 0;
    perf_report_request_time[1] = 0;
    perf_report_uri_rule[0] = 0;
    perf_report_uri_size[0] = 0;
    perf_report_uri_time[0] = 0;
    perf_report_uri_rule[1] = 0;
    perf_report_uri_size[1] = 0;
    perf_report_uri_time[1] = 0;
    perf_report_version_rule[0] = 0;
    perf_report_version_size[0] = 0;
    perf_report_version_time[0] = 0;
    perf_report_version_rule[1] = 0;
    perf_report_version_size[1] = 0;
    perf_report_version_time[1] = 0;
    perf_report_request_headers_rule[0] = 0;
    perf_report_request_headers_size[0] = 0;
    perf_report_request_headers_time[0] = 0;
    perf_report_request_headers_rule[1] = 0;
    perf_report_request_headers_size[1] = 0;
    perf_report_request_headers_time[1] = 0;
    perf_report_request_headers_rule[2] = 0;
    perf_report_request_headers_size[2] = 0;
    perf_report_request_headers_time[2] = 0;
    perf_report_request_headers_rule[3] = 0;
    perf_report_request_headers_size[3] = 0;
    perf_report_request_headers_time[3] = 0;
    perf_report_request_headers_rule[4] = 0;
    perf_report_request_headers_size[4] = 0;
    perf_report_request_headers_time[4] = 0;
    perf_report_response_rule[0] = 0;
    perf_report_response_size[0] = 0;
    perf_report_response_time[0] = 0;
    perf_report_response_rule[1] = 0;
    perf_report_response_size[1] = 0;
    perf_report_response_time[1] = 0;
    perf_report_status_rule[0] = 0;
    perf_report_status_size[0] = 0;
    perf_report_status_time[0] = 0;
    perf_report_status_rule[1] = 0;
    perf_report_status_size[1] = 0;
    perf_report_status_time[1] = 0;
    perf_report_reason_rule[0] = 0;
    perf_report_reason_size[0] = 0;
    perf_report_reason_time[0] = 0;
    perf_report_reason_rule[1] = 0;
    perf_report_reason_size[1] = 0;
    perf_report_reason_time[1] = 0;
    perf_report_response_headers_rule[0] = 0;
    perf_report_response_headers_size[0] = 0;
    perf_report_response_headers_time[0] = 0;
    perf_report_response_headers_rule[1] = 0;
    perf_report_response_headers_size[1] = 0;
    perf_report_response_headers_time[1] = 0;
    perf_report_response_headers_rule[2] = 0;
    perf_report_response_headers_size[2] = 0;
    perf_report_response_headers_time[2] = 0;
    perf_report_response_headers_rule[3] = 0;
    perf_report_response_headers_size[3] = 0;
    perf_report_response_headers_time[3] = 0;
    perf_report_response_headers_rule[4] = 0;
    perf_report_response_headers_size[4] = 0;
    perf_report_response_headers_time[4] = 0;
    perf_report_body_rule[0] = 0;
    perf_report_body_size[0] = 0;
    perf_report_body_time[0] = 0;
    perf_report_body_rule[1] = 0;
    perf_report_body_size[1] = 0;
    perf_report_body_time[1] = 0;
    perf_report_chunked_body_rule[0] = 0;
    perf_report_chunked_body_size[0] = 0;
    perf_report_chunked_body_time[0] = 0;
    perf_report_chunked_body_rule[1] = 0;
    perf_report_chunked_body_size[1] = 0;
    perf_report_chunked_body_time[1] = 0;
    perf_report_chunked_body_rule[2] = 0;
    perf_report_chunked_body_size[2] = 0;
    perf_report_chunked_body_time[2] = 0;
    perf_report_chunked_body_rule[3] = 0;
    perf_report_chunked_body_size[3] = 0;
    perf_report_chunked_body_time[3] = 0;
    perf_report_chunk_rule[0] = 0;
    perf_report_chunk_size[0] = 0;
    perf_report_chunk_time[0] = 0;
    perf_report_chunk_rule[1] = 0;
    perf_report_chunk_size[1] = 0;
    perf_report_chunk_time[1] = 0;
    perf_report_data__rule[0] = 0;
    perf_report_data__size[0] = 0;
    perf_report_data__time[0] = 0;
    perf_report_data__rule[1] = 0;
    perf_report_data__size[1] = 0;
    perf_report_data__time[1] = 0;
    perf_report_data_2_rule[0] = 0;
    perf_report_data_2_size[0] = 0;
    perf_report_data_2_time[0] = 0;
    perf_report_data_2_rule[1] = 0;
    perf_report_data_2_size[1] = 0;
    perf_report_data_2_time[1] = 0;
    perf_report_time_pointer = NULL;
    reflex::timer_start(perf_report_timer);
  }
 protected:
  size_t perf_report_INITIAL_rule[3];
  size_t perf_report_INITIAL_size[3];
  float  perf_report_INITIAL_time[3];
  size_t perf_report_request_rule[2];
  size_t perf_report_request_size[2];
  float  perf_report_request_time[2];
  size_t perf_report_uri_rule[2];
  size_t perf_report_uri_size[2];
  float  perf_report_uri_time[2];
  size_t perf_report_version_rule[2];
  size_t perf_report_version_size[2];
  float  perf_report_version_time[2];
  size_t perf_report_request_headers_rule[5];
  size_t perf_report_request_headers_size[5];
  float  perf_report_request_headers_time[5];
  size_t perf_report_response_rule[2];
  size_t perf_report_response_size[2];
  float  perf_report_response_time[2];
  size_t perf_report_status_rule[2];
  size_t perf_report_status_size[2];
  float  perf_report_status_time[2];
  size_t perf_report_reason_rule[2];
  size_t perf_report_reason_size[2];
  float  perf_report_reason_time[2];
  size_t perf_report_response_headers_rule[5];
  size_t perf_report_response_headers_size[5];
  float  perf_report_response_headers_time[5];
  size_t perf_report_body_rule[2];
  size_t perf_report_body_size[2];
  float  perf_report_body_time[2];
  size_t perf_report_chunked_body_rule[4];
  size_t perf_report_chunked_body_size[4];
  float  perf_report_chunked_body_time[4];
  size_t perf_report_chunk_rule[2];
  size_t perf_report_chunk_size[2];
  float  perf_report_chunk_time[2];
  size_t perf_report_data__rule[2];
  size_t perf_report_data__size[2];
  float  perf_report_data__time[2];
  size_t perf_report_data_2_rule[2];
  size_t perf_report_data_2_size[2];
  float  perf_report_data_2_time[2];
  float *perf_report_time_pointer;
  reflex::timer_type perf_report_timer;
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON BRIDGE LOCATIONS                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

typedef void *yyscan_t;
typedef HTTP_Reflex_Scanner_FlexLexer yyscanner_t;

#ifndef YY_EXTERN_C
#define YY_EXTERN_C
#endif

#else // !__cplusplus

typedef void *yyscan_t;

#undef YY_EXTERN_C
#define YY_EXTERN_C

#ifndef yy_size_t
#define yy_size_t size_t
#endif

YY_EXTERN_C char *HTTP_Reflex_Scanner_get_text(yyscan_t);
YY_EXTERN_C yy_size_t HTTP_Reflex_Scanner_get_leng(yyscan_t);
YY_EXTERN_C int HTTP_Reflex_Scanner_get_lineno(yyscan_t);
YY_EXTERN_C void HTTP_Reflex_Scanner_set_lineno(int, yyscan_t);
YY_EXTERN_C FILE *HTTP_Reflex_Scanner_get_in(yyscan_t);
YY_EXTERN_C void HTTP_Reflex_Scanner_set_in(FILE*, yyscan_t);
YY_EXTERN_C int HTTP_Reflex_Scanner_get_debug(yyscan_t);
YY_EXTERN_C void HTTP_Reflex_Scanner_set_debug(int, yyscan_t);
YY_EXTERN_C HTTP_Reflex_IParser* HTTP_Reflex_Scanner_get_extra(yyscan_t);
YY_EXTERN_C void HTTP_Reflex_Scanner_set_extra(HTTP_Reflex_IParser*, yyscan_t);

#endif // __cplusplus

YY_EXTERN_C int yylex(YYSTYPE*, YYLTYPE*, yyscan_t);
YY_EXTERN_C void yylex_init(yyscan_t*);
YY_EXTERN_C void yylex_init_extra(HTTP_Reflex_IParser*, yyscan_t*);
YY_EXTERN_C void yylex_destroy(yyscan_t);

#endif
