include (CMakeDependentOption)
include (FeatureSummary)

#include (OS)

set (CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${CMAKE_CURRENT_SOURCE_DIR}/../../modules/Common/src/dbus/scripts;${CMAKE_CURRENT_SOURCE_DIR}/../../../Common/src/dbus/scripts")
include (dbus)

if (UNIX)
 option (NETLINK_SUPPORT "enable netlink support" ON)

 set (WEXT_SUPPORT_ENABLE ON)
# check_library_exists (iw iw_sockets_open /usr/lib/x86_64-linux-gnu HAVE_LIBIW)
 set (IW_LIB_FILE libiw.so)
 find_library (IW_LIBRARY ${IW_LIB_FILE}
               PATHS /usr
               PATH_SUFFIXES lib64 lib
               DOC "searching for ${IW_LIB_FILE}")
 if (IW_LIBRARY)
  message (STATUS "Found iw library \"${IW_LIBRARY}\"")
 else ()
  message (WARNING "could not find ${IW_LIB_FILE}, continuing")
  set (WEXT_SUPPORT_ENABLE OFF)
 endif (IW_LIBRARY)
 option (WEXT_SUPPORT "enable Wext support" ${WEXT_SUPPORT_ENABLE})
 add_feature_info (Wext WEXT_SUPPORT "support wireless extensions")
 if (WEXT_SUPPORT)
  add_definitions (-DWEXT_SUPPORT)
 endif (WEXT_SUPPORT)

 set (NL80211_SUPPORT_ENABLE ON)
 pkg_check_modules (PKG_LIBNL3 libnl-3.0 libnl-genl-3.0)
 if (PKG_LIBNL3_FOUND)
#  message (STATUS "Found libnl-3.0")
 else ()
  message (WARNING "could not find libnl-3.0, continuing")
  pkg_check_modules (PKG_LIBNL2 libnl-2.0 libnl-genl-2.0)
  if (PKG_LIBNL2_FOUND)
#  message (STATUS "Found libnl-2.0")
  else ()
   message (WARNING "could not find libnl-2.0, continuing")
   set (NL80211_SUPPORT_ENABLE OFF)
  endif (PKG_LIBNL2_FOUND)
 endif (PKG_LIBNL3_FOUND)
# option (NL80211_SUPPORT "enable nl80211 support" ${NL80211_SUPPORT_ENABLE})
 CMAKE_DEPENDENT_OPTION (NL80211_SUPPORT "enable nl80211 support" ${NL80211_SUPPORT_ENABLE}
                         "NETLINK_SUPPORT" OFF)
 add_feature_info (nl80211 NL80211_SUPPORT "support nl80211")
 if (NL80211_SUPPORT)
  add_definitions (-DNL80211_SUPPORT)
 endif (NL80211_SUPPORT)

 set (NM_PKG_NAME "libnm")
 pkg_check_modules (PKG_NM ${NM_PKG_NAME})
 if (PKG_NM_FOUND)
  message (STATUS "found ${NM_PKG_NAME}")
 else ()
  message (WARNING "could not find ${NM_PKG_NAME}, continuing")
 endif (PKG_NM_FOUND)
 if (DBUS_SUPPORT AND PKG_NM_FOUND)
  option (DBUS_NM_SUPPORT "enable DBus/NetworkManager support" ON)
  add_feature_info (DBus/NetworkManager DBUS_NM_SUPPORT "support DBus/NetworkManager")
  if (DBUS_NM_SUPPORT)
   add_definitions (-DDBUS_NM_SUPPORT)
  endif (DBUS_NM_SUPPORT)
 endif (DBUS_SUPPORT AND PKG_NM_FOUND)
elseif (WIN32)
 option (WLANAPI_SUPPORT "compile wlanapi support" ON)
 add_feature_info (wlanapi WLANAPI_SUPPORT "support wlanapi")
 if (WLANAPI_SUPPORT)
  add_definitions (-DWLANAPI_SUPPORT)
 endif (WLANAPI_SUPPORT)
endif ()
