# *NOTE*: the first entry is the default option
if (UNIX)
 set (MONITOR_IMPLEMENTATION "nl80211" CACHE STRING "use nl80211 (default)")
 set (MONITOR_IMPLEMENTATION "Wext" CACHE STRING "use wireless extensions")
 set (MONITOR_IMPLEMENTATION "DBus" CACHE STRING "use DBus/NetworkManager")

 set_property (CACHE MONITOR_IMPLEMENTATION PROPERTY STRINGS "Wext" "nl80211" "DBus")
elseif (WIN32)
 set (MONITOR_IMPLEMENTATION "wlanapi" CACHE STRING "use wlanapi (default)")

 set_property (CACHE MONITOR_IMPLEMENTATION PROPERTY STRINGS "wlanapi")
endif ()

if (NOT (DEFINED MONITOR_IMPLEMENTATION_LAST))
 set (MONITOR_IMPLEMENTATION_LAST "NotAnImplementation" CACHE STRING "last monitor implementation used")
 mark_as_advanced (FORCE MONITOR_IMPLEMENTATION_LAST)
endif ()
if (NOT (${MONITOR_IMPLEMENTATION} MATCHES ${MONITOR_IMPLEMENTATION_LAST}))
 if (UNIX)
  unset (WEXT_USE CACHE)
  unset (NL80211_USE CACHE)
  unset (DBUS_USE CACHE)
 elseif (WIN32)
  unset (WLANAPI_USE CACHE)
 endif ()
  set (MONITOR_IMPLEMENTATION_LAST ${MONITOR_IMPLEMENTATION} CACHE STRING "Updating WLAN Monitor Implementation Option" FORCE)
endif ()

if (UNIX)
 if (${MONITOR_IMPLEMENTATION} MATCHES "Wext")
  if (NOT WEXT_SUPPORT)
   message (FATAL_ERROR "wext not supported")
  endif ()
  set (WEXT_USE ON CACHE STRING "use wireless extensions")
  mark_as_advanced (FORCE WEXT_USE)
  add_definitions (-DWEXT_USE)
 elseif (${MONITOR_IMPLEMENTATION} MATCHES "nl80211")
  if (NOT NL80211_SUPPORT)
   message (FATAL_ERROR "nl80211 not supported")
  endif ()
  set (NL80211_USE ON CACHE STRING "use nl80211")
  mark_as_advanced (FORCE NL80211_USE)
  add_definitions (-DNL80211_USE)
 elseif (${MONITOR_IMPLEMENTATION} MATCHES "DBus")
  if (NOT DBUS_SUPPORT)
   message (FATAL_ERROR "DBus/NetworkManager not supported")
  endif ()
  set (DBUS_USE ON CACHE STRING "use DBus/NetworkManager")
  mark_as_advanced (FORCE DBUS_USE)
  add_definitions (-DDBUS_USE)
 endif ()
elseif (WIN32)
 if (${MONITOR_IMPLEMENTATION} MATCHES "wlanapi")
  if (NOT WLANAPI_SUPPORT)
   message (FATAL_ERROR "wlanapi not supported")
  endif ()
  set (WLANAPI_USE ON CACHE STRING "use wlanapi")
  mark_as_advanced (FORCE WLANAPI_USE)
  add_definitions (-DWLANAPI_USE)
 endif ()
endif ()
