name: 'install_deps_win32'
description: 'install package dependencies on the runner'
inputs:
 os:
  description: 'runner OS'
  required: true
runs:
 using: "composite"
 steps:
  - uses: lukka/run-vcpkg@v11.5
    with:
     vcpkgDirectory: '${{ env.VCPKG_ROOT }}'
     vcpkgGitCommitId: '984f9232b2fe0eb94f5e9f161d6c632c581fff0c'
     runVcpkgInstall: true
     vcpkgJsonGlob: '**/vcpkg.json'
     doNotCache: false

  - run: choco install libreoffice-fresh libreoffice-sdk
    shell: cmd
