set (GEOIP2_SUPPORT_DEFAULT ON)
if (UNIX)
 pkg_check_modules (PKG_GEOIP2 GeoIp2)
 if (PKG_GEOIP2_FOUND)
  set (GEOIP2_FOUND TRUE)
  set (GEOIP2_INCLUDE_DIRS "${PKG_GEOIP2_INCLUDE_DIRS}")
  set (GEOIP2_LIBRARIES "${PKG_GEOIP2_LIBRARIES}")
 endif (PKG_GEOIP2_FOUND)
elseif (WIN32)
 if (VCPKG_SUPPORT)
#  cmake_policy (SET CMP0074 OLD)
  find_package (GeoIp2 CONFIG)
  if (GeoIp2_FOUND)
   set (GEOIP2_FOUND TRUE)
   set (GEOIP2_INCLUDE_DIRS "${GeoIp2_INCLUDE_DIRS}")
   set (GEOIP2_LIBRARIES "${GeoIp2_LIBRARIES}")
   if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR
       CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set (GEOIP2_LIB_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/debug/bin")
   else ()
    set (GEOIP2_LIB_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}/bin")
   endif ()
  endif (GeoIp2_FOUND)
 endif (VCPKG_SUPPORT)
 if (NOT GEOIP2_FOUND)
#  set (CMAKE_FIND_LIBRARY_SUFFIXES .lib .dll.a)
  find_library (GEOIP2_LIBRARY maxminddb.lib
                PATHS $ENV{LIB_ROOT}/libmaxminddb/build/msvc
                PATH_SUFFIXES ${CMAKE_BUILD_TYPE}
                DOC "searching for maxminddb.lib"
                NO_DEFAULT_PATH)
  if (NOT GEOIP2_LIBRARY)
   message (WARNING "could not find maxminddb.lib, continuing")
  else ()
   message (STATUS "Found maxminddb.lib library \"${GEOIP2_LIBRARY}\"")
   set (GEOIP2_FOUND TRUE)
   set (GEOIP2_INCLUDE_DIRS "$ENV{LIB_ROOT}/libmaxminddb/include")
   set (GEOIP2_LIBRARIES "${GEOIP2_LIBRARY}")
   set (GEOIP2_LIB_DIR "$ENV{LIB_ROOT}/libmaxminddb/build/msvc/${CMAKE_BUILD_TYPE}")
  endif (NOT GEOIP2_LIBRARY)
 endif (NOT GEOIP2_FOUND)
endif ()
if (GEOIP2_FOUND)
 option (GEOIP2_SUPPORT "enable GeoIp2 support" ${GEOIP2_SUPPORT_DEFAULT})
 if (GEOIP2_SUPPORT)
  add_definitions (-DGEOIP2_SUPPORT)
 endif (GEOIP2_SUPPORT)
endif (GEOIP2_FOUND)
