set (GEOIP2_SUPPORT_DEFAULT ON)
if (UNIX)
 pkg_check_modules (PKG_GEOIP2 libmaxminddb)
 if (PKG_GEOIP2_FOUND)
  set (GEOIP2_FOUND TRUE)
  set (GEOIP2_INCLUDE_DIRS "${PKG_GEOIP2_INCLUDE_DIRS}")
  set (GEOIP2_LIBRARIES "${PKG_GEOIP2_LIBRARIES}")
 else ()
  find_library (GEOIP2_LIBRARY libmaxminddb.a
                PATHS $ENV{LIB_ROOT}/libmaxminddb/src
                PATH_SUFFIXES .libs
                DOC "searching for libmaxminddb.a"
                NO_DEFAULT_PATH)
  if (NOT GEOIP2_LIBRARY)
   message (WARNING "could not find libmaxminddb.a, continuing")
  else ()
   message (STATUS "Found libmaxminddb.a library \"${GEOIP2_LIBRARY}\"")
   set (GEOIP2_FOUND TRUE)
   set (GEOIP2_INCLUDE_DIRS "$ENV{LIB_ROOT}/libmaxminddb/include")
   set (GEOIP2_LIBRARIES "${GEOIP2_LIBRARY}")
   set (GEOIP2_LIB_DIR "$ENV{LIB_ROOT}/libmaxminddb/src/.libs")
  endif (NOT GEOIP2_LIBRARY)
 endif (PKG_GEOIP2_FOUND)
elseif (WIN32)
 if (VCPKG_USE)
#  cmake_policy (SET CMP0074 OLD)
#  find_package (GeoIp2 CONFIG)
  find_library (MAXMINDDB_LIBRARY libmaxminddb.lib
                PATHS ${VCPKG_LIB_DIR}
                PATH_SUFFIXES lib
                DOC "searching for libmaxminddb.lib"
                NO_DEFAULT_PATH)
  if (MAXMINDDB_LIBRARY)
   set (GEOIP2_FOUND TRUE)
   set (GEOIP2_INCLUDE_DIRS ${VCPKG_INCLUDE_DIR_BASE})
   set (GEOIP2_LIBRARIES ${MAXMINDDB_LIBRARY})
   set (GEOIP2_LIB_DIR "${VCPKG_LIB_DIR}/bin")
  endif (MAXMINDDB_LIBRARY)
 endif (VCPKG_USE)
 if (NOT GEOIP2_FOUND)
  set (PATH_SUFFIX "Release")
  if (DEFINED CMAKE_BUILD_TYPE)
   set (PATH_SUFFIX ${CMAKE_BUILD_TYPE})
  endif (DEFINED CMAKE_BUILD_TYPE)
  find_library (GEOIP2_LIBRARY maxminddb.lib
                PATHS $ENV{LIB_ROOT}/libmaxminddb/build/msvc
                PATH_SUFFIXES ${PATH_SUFFIX}
                DOC "searching for maxminddb.lib"
                NO_DEFAULT_PATH)
  if (NOT GEOIP2_LIBRARY)
   message (WARNING "could not find maxminddb.lib, continuing")
  else ()
   message (STATUS "Found maxminddb.lib library \"${GEOIP2_LIBRARY}\"")
   set (GEOIP2_FOUND TRUE)
   set (GEOIP2_INCLUDE_DIRS "$ENV{LIB_ROOT}/libmaxminddb/include")
   set (GEOIP2_LIBRARIES "${GEOIP2_LIBRARY}")
   set (GEOIP2_LIB_DIR "$ENV{LIB_ROOT}/libmaxminddb/build/msvc/${PATH_SUFFIX}")
  endif (NOT GEOIP2_LIBRARY)
 endif (NOT GEOIP2_FOUND)
endif ()
if (GEOIP2_FOUND)
 option (GEOIP2_SUPPORT "enable GeoIp2 support" ${GEOIP2_SUPPORT_DEFAULT})
 if (GEOIP2_SUPPORT)
  add_definitions (-DGEOIP2_SUPPORT)
#  if (WIN32)
#   add_definitions (-DMMDB_UINT128_IS_BYTE_ARRAY)
#  endif (WIN32)
 endif (GEOIP2_SUPPORT)
endif (GEOIP2_FOUND)
