# This spec file was generated by KDevelop
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org>
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Name: libACENetwork
Version: 0.1
Release: 1
Vendor: N/A
Summary: (wrapper) library for network functionality, based on the ACE framework
(see: http://www.cs.wustl.edu/~schmidt/ACE.html). Specifically, the library
encapsulates descriptor-based (network) event propagation logic (i.e. user-space
dispatching APIs), as implemented and found on several common operating system
platforms. The library forsees dispatching these events using dedicated threads,
which facilitates efficient processing of data and communication protocols. In
conjunction with other (modularized) functionality
(see e.g.: https://github.com/esohns/libACEStream), this facilitates a modular
(i.e. less monolithic), and therefore reusable application design, which cleanly
separates network data from application-specific processing (i.e. business
logic).
License: LGPL
Distribution: N/A
#Icon: N/A
Group: Development/Libraries
Packager: Erik Sohns <eriksohns@123mail.org>
BuildRoot: %{_tmppath}/%{name}-root
Source: %{name}-%{version}.tar.gz
Provides: %{name}
AutoReqProv: yes
#Requires:
Prefix: /usr/local

%description
(wrapper) library for network functionality, based on the ACE framework

%prep
%setup -q
./autogen.sh

%build
mkdir build
cd build
../configure
cd ..
./scripts/generate_bindings.sh
cd build
make

%install
#rm -rf %{buildroot}
#cd build
%makeinstall

%clean
rm -rf %{buildroot}

%pre
%post -p /sbin/ldconfig
%verifyscript

%preun
%postun -p /sbin/ldconfig

%files
%defattr(-, root, root)
%doc AUTHORS ChangeLog INSTALL LICENSE NEWS README TODO
%{_bindir}/*
%{_includedir}/*
%{_libdir}/*
%{_datadir}/libACENetwork

%changelog
