# *NOTE*: the first entry is the default option
set (SCANNER_IMPLEMENTATION "flex" CACHE STRING "use flex (default)")
set (SCANNER_IMPLEMENTATION "reflex" CACHE STRING "use RE-flex")

set_property (CACHE SCANNER_IMPLEMENTATION PROPERTY STRINGS "flex" "reflex")

if (NOT DEFINED SCANNER_IMPLEMENTATION_LAST)
 set (SCANNER_IMPLEMENTATION_LAST "NotAnImplementation" CACHE STRING "last scanner implementation used")
 mark_as_advanced (FORCE SCANNER_IMPLEMENTATION_LAST)
endif (NOT DEFINED SCANNER_IMPLEMENTATION_LAST)
if (NOT (${SCANNER_IMPLEMENTATION} MATCHES ${SCANNER_IMPLEMENTATION_LAST}))
 unset (FLEX_USE CACHE)
 unset (REFLEX_USE CACHE)
 set (SCANNER_IMPLEMENTATION_LAST ${SCANNER_IMPLEMENTATION} CACHE STRING "Updating Scanner Implementation Option" FORCE)
endif (NOT (${SCANNER_IMPLEMENTATION} MATCHES ${SCANNER_IMPLEMENTATION_LAST}))

if (${SCANNER_IMPLEMENTATION} MATCHES "flex")
 if (NOT FLEX_SUPPORT)
  message (FATAL_ERROR "flex not supported")
 endif (NOT FLEX_SUPPORT)
 set (FLEX_USE ON CACHE STRING "use flex")
 mark_as_advanced (FORCE FLEX_USE)
 add_definitions (-DFLEX_USE)
elseif (${SCANNER_IMPLEMENTATION} MATCHES "reflex")
 if (NOT REFLEX_SUPPORT)
  message (FATAL_ERROR "RE-flex not supported")
 endif (NOT REFLEX_SUPPORT)
 set (REFLEX_USE ON CACHE STRING "use RE-flex")
 mark_as_advanced (FORCE REFLEX_USE)
 add_definitions (-DREFLEX_USE)
endif ()
