name: continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
      
 build:
  strategy:
   matrix:
    os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    platform: ['x86', 'x64']
    exclude:
     - os: 'ubuntu-latest'
       platform: 'x86'
     - os: 'windows-latest'
     - os: 'macos-latest'

  # The CMake configure and build commands are platform agnostic and should work equally
  # well on Windows or Mac.  You can convert this to a matrix build if you need
  # cross-platform coverage.
  # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  runs-on: ${{matrix.os}}

  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Checkout submodules
     run: git submodule update --init --recursive

   - name: Install dependencies (packages)
     uses: ./.github/actions/install_deps
     with:
      os: ${{matrix.os}}

   - name: Install dependencies (ACE)
     uses: ./.github/actions/install_ACE
     with:
      os: ${{matrix.os}}

   - name: Remove Common & ACEStream links
     if: ${{ matrix.os=='ubuntu-latest' }}
     run: |
          sudo rm -f modules/Common
          sudo rm -f modules/ACEStream

   - name: Checkout (Common)
     uses: actions/checkout@v2
     with:
      repository: esohns/Common
      path: modules/Common

   - name: Add Common link [UNIX]
     if: ${{ matrix.os=='ubuntu-latest' }}
     run: |
          cd ..
          sudo ln -s ACENetwork/modules/Common Common
          cd ${{github.workspace}}

   - name: Add Common link [Win32]
     if: ${{ matrix.os=='windows-latest' }}
     run: |
          cd ..
          mklink /D Common ACENetwork/modules/Common
          cd ${{github.workspace}}
     shell: cmd

   - name: Reset ACE link (Common) [UNIX]
     if: ${{ matrix.os=='ubuntu-latest' }}
     run: |
          sudo rm -f modules/Common/modules/ACE
          sudo ln -s /usr/include modules/Common/modules/ACE

   - name: Update git sub-modules (Common)
     run: |
          cd modules/Common
          git submodule update --init --recursive
          cd ${{github.workspace}}

   - name: Configure CMake (Common)
     run: |
          cd modules/Common
          cmake -B ${{github.workspace}}/modules/Common/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cd ${{github.workspace}}

   - name: Checkout (ACEStream)
     uses: actions/checkout@v2
     with:
      repository: esohns/ACEStream
      path: modules/ACEStream

   - name: Add Common link (ACEStream) [UNIX]
     if: ${{ matrix.os=='ubuntu-latest' }}
     run: |
          cd modules/ACEStream/modules
          sudo rm -f Common
          sudo ln -s ../../Common Common
          cd ${{github.workspace}}

   - name: Add Common link (ACEStream) [Win32]
     if: ${{ matrix.os=='windows-latest' }}
     run: |
          cd ..
          mklink /D Common ACEStream/modules/Common
          cd ${{github.workspace}}
     shell: cmd

   - name: Add ACEStream link [UNIX]
     if: ${{ matrix.os=='ubuntu-latest' }}
     run: |
          cd ..
          sudo ln -s ACENetwork/modules/ACEStream ACEStream
          cd ${{github.workspace}}

   - name: Add ACEStream link [Win32]
     if: ${{ matrix.os=='windows-latest' }}
     run: |
          cd ..
          mklink /D ACEStream ACENetwork/modules/ACEStream
          cd ${{github.workspace}}
     shell: cmd

   - name: Reset ACE link (ACEStream) [UNIX]
     if: ${{ matrix.os=='ubuntu-latest' }}
     run: |
          sudo rm -f modules/ACEStream/modules/ACE
          sudo ln -s /usr/include modules/ACEStream/modules/ACE

   - name: Apply Patch To (Temporarily) Remove Dependency on ACENetwork
     run: |
          cd modules/ACEStream
#          git apply -C3 --verbose scripts/github_repo_build.patch
          patch -f -p1 < scripts/github_repo_build.patch
          cd ${{github.workspace}}

   - name: Generate LibreOffice headers (ACEStream) [UNIX]
     if: ${{ matrix.os=='ubuntu-latest' }}
     run: |
          cd modules/ACEStream/scripts
          chmod u+x make_oo_headers.sh
          sudo ./make_oo_headers.sh
          cd ${{github.workspace}}

   - name: Generate LibreOffice headers (ACEStream) [Win32]
     if: ${{ matrix.os=='windows-latest' }}
     run: |
          cd modules/ACEStream/scripts
          .\\make_oo_headers.bat
          cd ${{github.workspace}}

   - name: Update git sub-modules (ACEStream)
     run: |
          cd modules/ACEStream
          git submodule update --init --recursive
          cd ${{github.workspace}}

   - name: Configure CMake (ACEStream)
     run: |
          cd modules/ACEStream
          cmake -B ${{github.workspace}}/modules/ACEStream/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cd ${{github.workspace}}

   - name: Configure CMake
     run: cmake -B ${{github.workspace}}/build -DCommon_DIR=modules/Common/build -DACEStream_DIR=modules/ACEStream/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

   - name: Build
     run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

   - name: Test
     working-directory: ${{github.workspace}}/build
     run: ctest -C ${{env.BUILD_TYPE}}
